name: package

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: DiogoRibeiro7/git-actions-collection/.github/actions/setup-poetry@v1
        with:
          python-version: "3.12"
          install-deps: "false"
      - name: Install dependencies
        run: poetry install
      - name: Build package
        run: poetry build
      - name: Upload dist artifacts
        uses: actions/upload-artifact@v7
        with:
          name: python-dist
          path: dist/
